Repository Utils4J/ReflectionUtils, pull requests merged in 2024-03, with the labels that each got.

#6 Add ReflectClass#isWildcard
  src/main/java/de/cyklon/reflection/entities/ReflectClass.java
  src/main/java/de/cyklon/reflection/entities/impl/ReflectClassImpl.java
Labels: type: bug, priority: normal, type: feature

#8 Add Unit Tests
  src/main/java/de/cyklon/reflection/entities/ReflectClass.java
  src/main/java/de/cyklon/reflection/entities/ReflectPackage.java
  src/main/java/de/cyklon/reflection/entities/impl/ReflectClassImpl.java
  src/main/java/de/cyklon/reflection/entities/members/ReflectField.java
  src/main/java/de/cyklon/reflection/entities/members/impl/ReflectConstructorImpl.java
  src/main/java/de/cyklon/reflection/entities/members/impl/ReflectFieldImpl.java
  src/main/java/de/cyklon/reflection/entities/members/impl/ReflectMethodImpl.java
  src/main/java/de/cyklon/reflection/exception/ClassNotFoundException.java
  src/main/java/de/cyklon/reflection/exception/ConstructorNotFoundException.java
  src/main/java/de/cyklon/reflection/types/AbstractMethod.java
  src/main/java/de/cyklon/reflection/types/Nameable.java
  src/test/java/ClassTest.java
  src/test/java/FieldTest.java
  src/test/java/GenericTest.java
  src/test/java/MethodTest.java
  src/test/java/PackageTest.java
Labels: type: improvement, priority: normal, type: feature

#4 Classfile
  src/main/java/de/cyklon/reflection/ReflectionUtils.java
  src/main/java/de/cyklon/reflection/entities/ClassFile.java
  src/main/java/de/cyklon/reflection/entities/OfflinePackage.java
  src/main/java/de/cyklon/reflection/entities/ReflectClass.java
  src/main/java/de/cyklon/reflection/entities/ReflectPackage.java
  src/main/java/de/cyklon/reflection/entities/impl/ClassFileImpl.java
  src/main/java/de/cyklon/reflection/entities/impl/OfflinePackageImpl.java
  src/main/java/de/cyklon/reflection/entities/impl/ReflectClassImpl.java
  src/main/java/de/cyklon/reflection/entities/impl/ReflectPackageImpl.java
  src/main/java/de/cyklon/reflection/exception/ClassNotFoundException.java
  src/main/java/de/cyklon/reflection/exception/MemberNotFoundException.java
  src/main/java/de/cyklon/reflection/exception/NotLoadedException.java
  src/main/java/de/cyklon/reflection/exception/PackageLoadException.java
  src/main/java/de/cyklon/reflection/exception/PackageNotFoundException.java
  src/main/java/de/cyklon/reflection/function/Filter.java
  src/main/java/de/cyklon/reflection/types/Loadable.java
  src/main/java/de/cyklon/reflection/types/Nameable.java
  src/main/java/module-info.java
  src/test/java/ClassTest.java
  src/test/java/GenericTest.java
  src/test/java/PackageTest.java
  src/test/java/test/TestClass.java
  src/test/java/test/TestPackage.java
  src/test/java/test/package-info.java
  src/test/java/test/t1/a.java
Labels: priority: normal, type: feature

#10 Package fix
  src/main/java/de/cyklon/reflection/entities/OfflinePackage.java
  src/main/java/de/cyklon/reflection/entities/ReflectPackage.java
  src/main/java/de/cyklon/reflection/entities/impl/OfflinePackageImpl.java
  src/main/java/de/cyklon/reflection/entities/impl/ReflectPackageImpl.java
Labels: type: bug, type: improvement, priority: high

#11 Filter Improve
  src/main/java/de/cyklon/reflection/function/Filter.java
Labels: type: improvement, priority: normal

#12 Sorter
  src/main/java/de/cyklon/reflection/entities/impl/ReflectClassImpl.java
  src/main/java/de/cyklon/reflection/entities/members/impl/ReflectConstructorImpl.java
  src/main/java/de/cyklon/reflection/entities/members/impl/ReflectFieldImpl.java
  src/main/java/de/cyklon/reflection/entities/members/impl/ReflectMethodImpl.java
  src/main/java/de/cyklon/reflection/entities/members/impl/ReflectParameterImpl.java
  src/main/java/de/cyklon/reflection/function/Sorter.java
  src/main/java/de/cyklon/reflection/types/Modifiable.java
Labels: priority: normal, type: feature
